const fs = require('fs');
const f = 'shaders/bufferA.frag';
let T = fs.readFileSync(f, 'utf8');
const bal = (s) => { const o=(s.match(/{/g)||[]).length, c=(s.match(/}/g)||[]).length, p=(s.match(/\(/g)||[]).length, q=(s.match(/\)/g)||[]).length; return {ok:o===c&&p===q}; };
const must = (c,m) => { if(!c){console.log('ABORT: '+m);process.exit(1);} };
const rep = (a, b, tag) => { const n = T.split(a).length - 1; must(n === 1, tag + ': found ' + n); T = T.split(a).join(b); console.log('ok: ' + tag); };
rep('  if (uDebug == 28) {', '  if (uDebug == 29) {\n    float fpX;\n    mat4 gX, gXr, gXt, gXu; knMetricDR(6.0, 1.2, gX, gXr, gXt, gXu);\n    vec4 pCovX = vec4(-1.0, 0.3, 0.2, 3.0);\n    vec4 bPhi = gX * vec4(0.0, 0.0, 0.0, 1.0);\n    vec4 fX = knPolFromB(pCovX, bPhi, 6.0, 1.2);\n    col = vec3(0.25, clamp(0.5 + fX.y, 0.0, 1.0), clamp(0.5 + fX.z, 0.0, 1.0));\n  } else if (uDebug == 28) {', 'view 29');
const b = bal(T); console.log('balance', JSON.stringify(b));
must(b.ok, 'unbalanced');
fs.writeFileSync(f, T); console.log('WROTE');